#
# Makefile generated by gec.
#

.PHONY: all install clean distclean uninstall

all: aop

prefix = /usr/local
exec_prefix = $(prefix)
bindir = $(exec_prefix)/bin
mandir = $(prefix)/man
man1dir = $(mandir)/man1

INSTALL = install -C
INSTALL_PROGRAM = $(INSTALL)
INSTALL_DATA = $(INSTALL)

CFLAGS += `/home/agarciafdz/Eiffel_22.05/library/base/elks/encoding/implementation/unix/Clib/iconv-config --include_path` -I"/home/agarciafdz/Eiffel_22.05/library/base/elks/encoding/implementation/include" -I"/home/agarciafdz/Eiffel_22.05/library/time/spec/include" 
LDFLAGS += `/home/agarciafdz/Eiffel_22.05/library/base/elks/encoding/implementation/unix/Clib/iconv-config --library` `/home/agarciafdz/Eiffel_22.05/library/net/Clib/net-config --library` 
LDLIBS += -lm  
OBJS = aop1.o "/home/agarciafdz/Eiffel_22.05/library/net/spec/linux-x86-64/lib/libmtnet.a"

aop: $(OBJS) aop.h
	$(CC) $(LDFLAGS) -o aop $(OBJS) $(LDLIBS)

clean:
	-rm $(OBJS) aop

distclean: clean

install:
	$(INSTALL_PROGRAM) -d $(DESTDIR)$(bindir)
	$(INSTALL_PROGRAM) aop $(DESTDIR)$(bindir)

uninstall:
	-rm -f $(DESTDIR)$(bindir)/aop

.c.o:
	$(CC) $(CFLAGS) -c $<
