#
# Makefile generated by gec.
#

.PHONY: all install clean distclean uninstall

all: AOP

prefix = /usr/local
exec_prefix = $(prefix)
bindir = $(exec_prefix)/bin
mandir = $(prefix)/man
man1dir = $(mandir)/man1

INSTALL = install -C
INSTALL_PROGRAM = $(INSTALL)
INSTALL_DATA = $(INSTALL)

CFLAGS += `/home/agarciafdz/Eiffel_22.05/library/base/elks/encoding/implementation/unix/Clib/iconv-config --include_path` -I"/home/agarciafdz/Eiffel_22.05/library/base/elks/encoding/implementation/include" 
LDFLAGS += `/home/agarciafdz/Eiffel_22.05/library/base/elks/encoding/implementation/unix/Clib/iconv-config --library` 
LDLIBS += -lm  
OBJS = AOP1.o

AOP: $(OBJS) AOP.h
	$(CC) $(LDFLAGS) -o AOP $(OBJS) $(LDLIBS)

clean:
	-rm $(OBJS) AOP

distclean: clean

install:
	$(INSTALL_PROGRAM) -d $(DESTDIR)$(bindir)
	$(INSTALL_PROGRAM) AOP $(DESTDIR)$(bindir)

uninstall:
	-rm -f $(DESTDIR)$(bindir)/AOP

.c.o:
	$(CC) $(CFLAGS) -c $<
