name: Run Nushell Script

on:
  push:
  workflow_dispatch:

jobs:
  run_nushell_script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install tokei
        run: |
          cargo install tokei --features all

      - uses: hustcer/setup-nu@v3
        with:
          version: "0.90" # Don't use 0.90 here, as it was a float number and will be convert to 0.9, you can use v0.90/0.90.0 or '0.90'
      - run: print $'Nu version info:(char nl)'; version
        shell: nu {0}
      - name: Default shell will be `nu`
        shell: nu {0}
